# Netlify Configuration für AI Chatbot Portfolio

[build]
  # Build command für Static Site
  command = "echo 'Static site build complete'"
  # Publish directory (Hauptverzeichnis da alles bereits dort liegt)
  publish = "."
  # Functions directory für Serverless Functions
  functions = "netlify/functions"

[build.environment]
  # Node.js Version
  NODE_VERSION = "18"
  # Groq API Key - Set in Netlify Dashboard Environment Variables
  # GROQ_API_KEY = "your-groq-api-key-here"

# Redirect Rules für SPA-ähnliches Verhalten
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Function settings
[functions]
  # Increase timeout for chat function
  directory = "netlify/functions"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Chat API specific headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Edge functions for chat responses (optional optimization)
# [[edge_functions]]
#   function = "chat-edge"
#   path = "/api/chat"

# Environment-specific configuration
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Form handling (if needed for contact forms)
[forms]
  # Optional: Enable Netlify Forms if contact form is added

# Plugin configuration (optional)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"